# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# oooooh, these are like globals
version: 0.1.0  # what version - see changelog
title: blog (anthony's)
email: anthony.tan@greenworm.net
description: >- # this means to ignore newlines until "baseurl:"
  A collection of notes that probably deserves a better home than being in the form of textfiles 
  and archives sitting on my desktop at home.
author: "email:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://greenworm.net" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: anthony.tan
youtube_username: tanantish
github_username:  tanant
imdb_nicename: Anthony Tan  # use this to display something nicer
imdb_username: nm7533028  # the werid imDB name thing
linkedin_nicename: Anthony Tan  # use this to display something nicer for linkedin
linkedin_username: tanant  # the annoying linked thing as well

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
 - index.html
 - pages/about.markdown
 - pages/diagnostics.markdown


paginate: 8
markdown: kramdown

google_analytics: G-DF9MX5M13P


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
